# Jekyll configuration for GitHub Pages
title: Saroop Singh Newspaper Archive
description: Historical newspaper archive of athletic meet clippings from Malayan newspapers (1937-1954)
baseurl: "/saroop-singh-newspaper-archive"
url: "https://lifeofgurpreet.github.io"

# Theme - removed for custom layout
# theme: minima

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  articles:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: "output/articles"
      type: "pages"
    values:
      layout: "article"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Plugins (removed unsupported plugins)
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-sitemap

# Exclude files
exclude:
  - .obsidian
  - ai-system-prompts
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock
  - vendor# Rebuild trigger Sun Aug 31 01:37:05 +11 2025
